version: 0.2

phases:
  install:
    commands:
      - ansible --version
      - packer --version
      - aws --version
  build:
    commands:
      - echo "$VAULT_PASS" > vault_password_file
      - /bin/sh scripts/run.sh
